### ISSUE TITLE
No Tagged release in upstream

### ISSUE THREAD

**Issue by sparshg** [flathub/org.sugarlabs.SwiftFeet#5]
@chimosky @tchx84 We need to create a tagged release in the [upstream](https://github.com/sugarlabs/swiftfeet-activity) so that data checkers can be added

**Comment by chimosky** [comment]
Upstream now has a v2 tag, and upstream would've been the best place for this issue.

**Comment by sparshg** [comment]
There was no issue tab in the upstream so @tchx84 asked me to make one here

**Comment by chimosky** [comment]
Okay, makes sense.

I've requested for transfer of ownership of the repo as the one we have is a fork and I'm guessing that's why there are no issues.
